### ISSUE TITLE
Pc and Android?

### ISSUE THREAD

**Issue by rp1231** [jfedor2/screen-hopper#1]
Would it be possible to use this with a pc and Android device?

**Comment by jfedor2** [comment]
Unfortunately Android doesn't seem to support absolute mouse cursor positioning so it will not work in its current form.

**Comment by rp1231** [comment]
Ah I see, Thanks.

**Comment by rp1231** [comment]
I'm not really a dev, but there is some sort of mention for absolute positioning on this page.
https://developer.android.com/reference/android/database/Cursor#moveToPosition(int)

Maybe it would be possible with this?

**Comment by rp1231** [comment]
@jfedor2  Do you think it would be possible in Android OTG mode?
