### ISSUE TITLE
Support for other RP2040-derived boards?

### ISSUE THREAD

**Issue by blalor** [jfedor2/screen-hopper#2]
How tied to the Pico hardware is this project?  Would it be possible to use other RP2040-using boards like Adafruit's [KB2040](https://www.adafruit.com/product/5302)?

**Comment by jfedor2** [comment]
There's nothing Pico-specific here, you can use any RP2040-based board. Worst case scenario you'll have to recompile the firmware if the same GPIO pins aren't exposed on your particular board.

**Comment by jfedor2** [comment]
The only thing that comes to mind is that some boards don't "back-power" the USB port when they're powered from the 5V pin. For example on Adafruit's QT Py RP2040 you'd have to solder a jumper on the back of the board if you wanted to use it as the "B" side. This only applies to the triple-RP2040 version.

**Comment by blalor** [comment]
Awesome! Thanks. The QT Py would be nice for its compact form factor…

Do the USB-C connectors on the Adafruit boards still need an OTG adapter, or does that negotiate automatically?

**Comment by jfedor2** [comment]
> Do the USB-C connectors on the Adafruit boards still need an OTG adapter, or does that negotiate automatically?

If you have a mouse or some other device that uses USB-C, you can connect it directly.

**Comment by blalor** [comment]
Thank you!
