### ISSUE TITLE
Changing GPIO Pins

### ISSUE THREAD

**Issue by maxexcloo** [jfedor2/screen-hopper#5]
I'm looking to build this using this RP2040 module (for size): https://www.waveshare.com/wiki/RP2040-Zero

I think it should be okay except that GPIO20 won't be easy to access, do you have any tips?

Awesome project btw!

**Comment by jfedor2** [comment]
Just change FORWARDER_TX_PIN in remapper.cc and recompile. Just keep in mind it has to be one of the UART1 TX pins.

**Comment by maxexcloo** [comment]
Appreciate the help as I'm new to the whole environment - will report back how it all goes :)

**Comment by maxexcloo** [comment]
I've built a board and recompiled using GPIO9 of RP2040-Zero:

![](https://core-electronics.com.au/attachments/localcontent/ce08607-rp2040-zero-pinout_3130485a4f6.jpg)

I tried to match the pin with one with similar capabilities to the original board - however I've noticed GPIO20 on the original pico isn't UART (according to the data sheet: https://datasheets.raspberrypi.com/pico/pico-datasheet.pdf)?

Input from screenhopper_a is working, just not from forwarder.uf2 - is there anything basic I'm missing? This is amazing btw! Great docs and I'm having a ton of fun with it!

**Comment by maxexcloo** [comment]
In case you're curious how it looks with a RP2040-Zero:

[
![71621236733__ABFE21F6-5D06-4496-936C-5ECCC15FA327](https://github.com/jfedor2/screen-hopper/assets/927210/36565dd6-7222-43d1-b901-62d38c266003)
](url)

**Comment by maxexcloo** [comment]
Circuit layout is this AFAIK:

![Schematic_Screen Hopper_2023-09-12](https://github.com/jfedor2/screen-hopper/assets/927210/ccf94649-3af3-4f35-ae9b-d99872282f2a)

**Comment by jfedor2** [comment]
GPIO9 is RX.

You can use these pins for UART1 TX: 4, 8, 20, 24.
