### ISSUE TITLE
Use Only Hotkey to Swap Screen

### ISSUE THREAD

**Issue by maxexcloo** [jfedor2/screen-hopper#6]
Another question, I've been trying to work out how to configure my settings to only swap screens on hotkey press - that is, no smart screen swapping as I often have different sized monitors.

Is there any recommended way to do this?

**Comment by jfedor2** [comment]
If you configure the screens so that they don't touch each other (there's a gap) and select the "restrict to screens" option then it will not be possible to drag the cursor from one screen to the other.
